In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Multi-Touch Marketing Attribution Project

## Data Loading and Inspection

In [5]:
ad_spend = pd.read_csv("../data/ad_spend.csv")
web_analytics = pd.read_csv("../data/web_analytics.csv")
crm_conversions = pd.read_csv("../data/crm_conversions.csv")

NameError: name 'pd' is not defined

In [6]:
pd

NameError: name 'pd' is not defined

In [7]:
import pandas as pd

In [8]:
pd

In [9]:
ad_spend = pd.read_csv("../data/ad_spend.csv")
web_analytics = pd.read_csv("../data/web_analytics.csv")
crm_conversions = pd.read_csv("../data/crm_conversions.csv")

In [10]:
ad_spend.head()

         date     channel  spend  clicks
0  2025-01-01  Google Ads   1394     341
1  2025-01-01    Facebook    862     849
2  2025-01-01    LinkedIn    813     612
3  2025-01-01      TikTok   2206     266
4  2025-01-02  Google Ads   3965     869

In [11]:
ad_spend.shape

(720, 4)

In [12]:
ad_spend.columns

Index(['date', 'channel', 'spend', 'clicks'], dtype='str')

In [13]:
ad_spend.info()

<class 'pandas.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     720 non-null    str
 1   channel  720 non-null    str
 2   spend    720 non-null    int64
 3   clicks   720 non-null    int64
dtypes: int64(2), str(2)
memory usage: 22.6 KB

In [1]:
web_analytics.head()

NameError: name 'web_analytics' is not defined

In [2]:
import pandas as pd

In [3]:
ad_spend = pd.read_csv("../data/ad_spend.csv")
web_analytics = pd.read_csv("../data/web_analytics.csv")
crm_conversions = pd.read_csv("../data/crm_conversions.csv")

In [4]:
web_analytics.head()

   user_id   timestamp         channel                 campaign
0  U100000  2025-04-03        LinkedIn        LinkedIn_Campaign
1  U100000  2025-04-04  Organic Search  Organic_Search_Campaign
2  U100000  2025-04-05  Organic Search  Organic_Search_Campaign
3  U100000  2025-04-06        Facebook        Facebook_Campaign
4  U100001  2025-03-16        LinkedIn        LinkedIn_Campaign

In [5]:
web_analytics.shape

(14911, 4)

In [6]:
web_analytics.info()

<class 'pandas.DataFrame'>
RangeIndex: 14911 entries, 0 to 14910
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   user_id    14911 non-null  str
 1   timestamp  14911 non-null  str
 2   channel    14911 non-null  str
 3   campaign   14911 non-null  str
dtypes: str(4)
memory usage: 466.1 KB

In [7]:
crm_conversions.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          1200 non-null   str
 1   conversion_date  1200 non-null   str
 2   revenue          1200 non-null   int64
dtypes: int64(1), str(2)
memory usage: 28.3 KB

In [8]:
crm_conversions.head()

   user_id conversion_date  revenue
0  U102308      2025-02-07      945
1  U100408      2025-07-09      979
2  U103528      2025-04-21      686
3  U102747      2025-07-18      975
4  U102664      2025-07-22      580